spring:
  application:
    name: cloud-feign
  #服务链路追踪配置
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8766


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Feign 是自带熔断器的，但默认是关闭的，打开
feign:
  hystrix:
    enabled: true